### ISSUE TITLE
ValueError: Input 0 of layer "sequential" is incompatible with the layer: expected shape=(None, 20), found shape=(None, 5)

### ISSUE THREAD

**Issue by Jonypoi81** [Jonypoi81/ANN-Model-in-Python#1]
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.metrics import mean_squared_error, mean_absolute_error
from datetime import date, timedelta, datetime
%matplotlib inline
import seaborn as sns
[ECOW.csv](https://github.com/Jonypoi81/ANN-Model-in-Python/files/8243745/ECOW.csv)

filename = "ECOW.csv"
STORAGE_FOLDER = ""
data = pd.read_csv("ECOW.csv")
data.tail(10)

data.shape

# to print the full summary
data.info()

# knowling number of non-missing values for each variable
data.isnull().sum()

data = data.drop(labels=2481, axis=0)
data.shape

train_df = data.sort_values(by=['Date']).copy()
# We safe a copy of the dates index, before we need to reset it to numbers
date_index = train_df.index
X = data.drop(columns=['Date', 'Value'], axis=1)
Y = data['Value']
X_train = X.loc[:2000, : ]
Y_train = Y.loc[:2000]
X_test = X.loc[2000:, :]
Y_test = Y.loc[2000:]
print(X.shape, X_train.shape, X_test.shape)
print(Y.shape, Y_train.shape, Y_test.shape)

scaler = MinMaxScaler()
#scaler = StandardScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)
print(X_train)

from keras.models import Sequential, load_model
from keras.layers import Dense
from keras.layers import Dropout
from keras.callbacks import EarlyStopping

classifier = Sequential()
classifier.add(Dense(units = 128, activation = 'relu', input_dim=20))
classifier.add(Dropout(rate = 0.5))
classifier.add(Dense(units = 128, activation = 'relu'))
classifier.add(Dropout(rate = 0.5))

#classifier.add(Dense(units = 256, activation = 'relu'))
#classifier.add(Dropout(rate = 0.1))
classifier.add(Dense(units = 128, activation = 'relu'))
classifier.add(Dropout(rate = 0.5))
classifier.add(Dense(units = 1, activation = 'relu'))
classifier.compile(optimizer = 'adam', loss = 'mean_absolute_error', metrics=['mean_absolute_error'])
es = EarlyStopping(monitor='val_loss', mode='min', verbose=2, patience=200)
classifier.summary()

history = classifier.fit(X_train,Y_train,epochs=150, batch_size=60, validation_data=(X_test, Y_test), callbacks=[es])

ValueError                                Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_37776/1568418661.py in <module>
----> 1 history = classifier.fit(X_train,Y_train,epochs=150, batch_size=60, validation_data=(X_test, Y_test), callbacks=[es])

~\anaconda3\lib\site-packages\keras\utils\traceback_utils.py in error_handler(*args, **kwargs)
     65     except Exception as e:  # pylint: disable=broad-except
     66       filtered_tb = _process_traceback_frames(e.__traceback__)
---> 67       raise e.with_traceback(filtered_tb) from None
     68     finally:
     69       del filtered_tb

~\anaconda3\lib\site-packages\tensorflow\python\framework\func_graph.py in autograph_handler(*args, **kwargs)
   1145           except Exception as e:  # pylint:disable=broad-except
   1146             if hasattr(e, "ag_error_metadata"):
-> 1147               raise e.ag_error_metadata.to_exception(e)
   1148             else:
   1149               raise

ValueError: in user code:

    File "C:\Users\JonyPoi\anaconda3\lib\site-packages\keras\engine\training.py", line 1021, in train_function  *
        return step_function(self, iterator)
    File "C:\Users\JonyPoi\anaconda3\lib\site-packages\keras\engine\training.py", line 1010, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "C:\Users\JonyPoi\anaconda3\lib\site-packages\keras\engine\training.py", line 1000, in run_step  **
        outputs = model.train_step(data)
    File "C:\Users\JonyPoi\anaconda3\lib\site-packages\keras\engine\training.py", line 859, in train_step
        y_pred = self(x, training=True)
    File "C:\Users\JonyPoi\anaconda3\lib\site-packages\keras\utils\traceback_utils.py", line 67, in error_handler
        raise e.with_traceback(filtered_tb) from None
    File "C:\Users\JonyPoi\anaconda3\lib\site-packages\keras\engine\input_spec.py", line 264, in assert_input_compatibility
        raise ValueError(f'Input {input_index} of layer "{layer_name}" is '

    ValueError: Input 0 of layer "sequential" is incompatible with the layer: expected shape=(None, 20), found shape=(None, 5)

**Comment by Jonypoi81** [comment]
I can't figure out how to debug it
